// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FileOpener is an autogenerated mock type for the FileOpener type
type FileOpener struct {
	mock.Mock
}

// OpenFile provides a mock function with given fields: pth
func (_m *FileOpener) OpenFile(pth string) (io.Reader, error) {
	ret := _m.Called(pth)

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.Reader, error)); ok {
		return rf(pth)
	}
	if rf, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = rf(pth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFileOpener interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileOpener creates a new instance of FileOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileOpener(t mockConstructorTestingTNewFileOpener) *FileOpener {
	mock := &FileOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
